#!/usr/bin/env sh

set -e

run() {
	local log="$1"
	echo "$log..." >&2
	shift
	"$@"
	e=$?
	echo "$log done" >&2

	return $e
}

run "creating docs directory" mkdir -p /usr/share/doc/ella
run "installing binary" install -Dm755 ella /usr/bin/ella
run "installing fsm docs" install -Dm644 fsm/*.png /usr/share/doc/ella/
run "installing bash completion" install -Dm644 completion.sh /etc/bash_completion.d/ella
