# -----------------------------------------------------------------------------
# Portions of this file are Copyright (c) 2015-2025 fatedier <fatedier@gmail.com>
# Original work licensed under the Apache License 2.0
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Modifications (c) 2025 Pooyan
# Licensed under the MIT License
#
# You may obtain a copy of the MIT License at:
#     https://opensource.org/licenses/MIT
#
# Description:
# This file is based on FRP (https://github.com/fatedier/frp) and has been
# modified for use in my project.
# -----------------------------------------------------------------------------

name: goreleaser

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-gomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gomod-

      - name: Cache Go bin
        uses: actions/cache@v4
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-gobin-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-gobin-

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Update apt cache
        run: sudo apt-get update

      - name: Install Graphviz
        run: sudo apt-get install -y graphviz

      - name: Install go-jsonschema
        run: |
          if ! command -v go-jsonschema >/dev/null; then
            go install github.com/atombender/go-jsonschema@latest
          fi

      - name: Install stringer
        run: |
          if ! command -v stringer >/dev/null; then
            go install golang.org/x/tools/cmd/stringer@latest
          fi

      - name: Build packages
        run: ./ci/goreleaser/package.sh

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
